[package]
name = "window_manager"
version = "0.1.0"
edition = "2021"
links = "X11"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11 = "2.19.1"
log = "0.4.16"
log4rs = "1.1.1"
rand = "0.8.5"
libc = "0.2.65"

