# TODO: use this
# It's in this commit because I don't want to delete it again

[palette]
dark_text = "#030405"
light_text = "#E7E8E9"
accent = "#428BCA"
button_normal = "#030405"

[misc]
background = "#111111"

[window]
focused = "accent"
focused_text = "dark_text"
normal = "#777777"
normal_text = "dark_text"
selected = "#5CB85C"
selected_text = "dark_text"
urgent = "#D9534F"
urgent_text = "dark_text"
close_button = "button_normal"
close_button_hovered = "#FF3B30"
maximize_button = "button_normal"
maximize_button_hovered = "#28CD41"
minimize_button = "button_normal"
minimize_button_hovered = "#FFCC00"

[bar]
background = "#161514"
text = "light_text"

[notifications]
background = "#1F1F1F"
